/**
 * ====================================================
 *  QLIKARD — POSTS DATABASE
 * ====================================================
 *  To add a new post:
 *  1. Copy post-template.html to posts/your-slug.html
 *  2. Fill in the content
 *  3. Add an entry to the POSTS array below
 * ====================================================
 */

const CATEGORIES = {
  scripts:  { label: 'Scripts',        color: 'scripts'  },
  viz:      { label: 'Visualizations', color: 'viz'      },
  automate: { label: 'Qlik Automate',  color: 'automate' },
  general:  { label: 'General Tips',   color: 'general'  },
};

const POSTS = [
  {
    id: 'incremental-load-qvd-tags',
    title: 'Smart Incremental Loads — Frequency-Based Full Reloads with QVD Tags',
    excerpt: 'Getting the incremental start time is the easy part. Knowing when to do a full reload is harder — and different tables need different frequencies. This pattern stores a FullReloadDate tag inside each QVD header and reads it back to decide automatically.',
    category: 'scripts',
    date: '2026-04-14',
    file: 'posts/incremental-load-qvd-tags.html',
    readTime: 8,
  },
  {
    id: 'split-automation-memory-limit',
    title: 'Beat the Memory Limit — Split Report Automations in Two',
    excerpt: 'Building reports for many recipients in a single automation run eventually hits the memory limit. The fix: one orchestrator automation that loops through recipients, and one report automation that builds and sends for a single recipient. Each call runs clean with the full memory budget.',
    category: 'automate',
    date: '2026-04-13',
    file: 'posts/split-automation-memory-limit.html',
    readTime: 5,
  },
  {
    id: 'filter-list-to-qlik-selection',
    title: 'Turn a Comma-Separated Excel Filter into a Qlik Report Selection',
    excerpt: 'Report config stored in Excel often has multiple filter values in one cell, separated by commas. This automation converts that raw string into the "val1","val2","val3" format that Add Selection To Chart expects — and checks whether there\'s actually data before sending.',
    category: 'automate',
    date: '2026-04-13',
    file: 'posts/filter-list-to-qlik-selection.html',
    readTime: 6,
  },
  {
    id: 'autonumber-load-vs-statement',
    title: 'Autonumber During LOAD vs After — Which Is Faster?',
    excerpt: 'Two ways to autonumber key fields: inline in the LOAD, or with a wildcard statement after. The inline approach is 30% faster because it avoids a second pass over the data. Plus: why a company prefix matters, and how to exclude all keys from Smart Search in one line.',
    category: 'scripts',
    date: '2026-04-13',
    file: 'posts/autonumber-load-vs-statement.html',
    readTime: 5,
  },
  {
    id: 'graphql-in-qlik-script',
    title: 'Calling GraphQL APIs from Qlik Script',
    excerpt: 'GraphQL is just HTTP POST with a JSON body — but embedding that body safely in a Qlik script requires handling whitespace and quote escaping. One utility subroutine solves it once, and a clean query-per-subroutine pattern keeps the rest of the script readable.',
    category: 'scripts',
    date: '2026-04-13',
    file: 'posts/graphql-in-qlik-script.html',
    readTime: 7,
  },
  {
    id: 'left-join-calculated-field',
    title: 'Skip the RENAME — Add Calculated Fields with LEFT JOIN Instead',
    excerpt: 'The RENAME + LOAD * + DROP pattern works, but it reloads every field on every row just to add one column. If your table has a unique key, a LEFT JOIN loading only the key and the new field is 2.7× faster on 10M rows.',
    category: 'scripts',
    date: '2026-04-13',
    file: 'posts/left-join-calculated-field.html',
    readTime: 5,
  },
  {
    id: 'self-service-reload-monitor',
    title: 'Monitoring Self-Service Reloads with Qlik Automate',
    excerpt: 'Built-in reload alerts have gaps — limited channels, no stale-app detection, no consolidated view. This automation scans your spaces on a schedule, flags failed or overdue apps, and sends a formatted email summary with direct links to each app\'s reload history.',
    category: 'automate',
    date: '2026-04-10',
    file: 'posts/self-service-reload-monitor.html',
    readTime: 8,
  },
  {
    id: 'script-timer-subroutine',
    title: 'Script Timers — Know Exactly How Long Every Section Takes',
    excerpt: 'Two subroutines you write once: StartTimer and EndTimer. Call them around any section to get duration in the reload log and a TimerLog table in your model. Combine with Execute_Sub and every subroutine gets timed automatically.',
    category: 'scripts',
    date: '2026-04-10',
    file: 'posts/script-timer-subroutine.html',
    readTime: 6,
  },
  {
    id: 'dollar-sign-master-measure-total',
    title: '$(=MasterMeasure) — One Source of Truth for Totals',
    excerpt: 'SUM(TOTAL ...) duplicates your formula everywhere you need a grand total. $(=MasterMeasureName) gives the same result by evaluating the master measure at chart level — one definition, maintained in one place.',
    category: 'viz',
    date: '2026-04-10',
    file: 'posts/dollar-sign-master-measure-total.html',
    readTime: 5,
  },
  {
    id: 'variable-function-color-gradient',
    title: '$1 in Variables — Dynamic Gradient Colors in Qlik Tables',
    excerpt: 'Variables with $1 act like functions — pass arguments at call time. Here\'s how to use that to build a background color that automatically deepens based on each row\'s share of the total, with no conditional rules needed.',
    category: 'viz',
    date: '2026-04-10',
    file: 'posts/variable-function-color-gradient.html',
    readTime: 6,
  },
  {
    id: 'orderby-groupby-benchmark',
    title: 'Does Pre-Sorting Speed Up GROUP BY in Qlik?',
    excerpt: 'ORDER BY before GROUP BY — does it actually help? I tested four aggregation scenarios on 10M rows, with and without pre-sorting. Pre-sorting won every time, and the reasons why are worth understanding.',
    category: 'scripts',
    date: '2026-04-10',
    file: 'posts/orderby-groupby-benchmark.html',
    readTime: 7,
  },
  {
    id: 'progress-bar-in-table',
    title: 'How to Create a Progress Bar Inside a Qlik Table',
    excerpt: 'No extensions needed. Build an inline bar column using an HTML expression and one setting change — Representation set to Text.',
    category: 'viz',
    date: '2026-04-03',
    file: 'posts/progress-bar-in-table.html',
    readTime: 5,
  },
  {
    id: 'build-null-table',
    title: 'BuildNullTable — Handle Missing Dimension Keys Automatically',
    excerpt: 'Fact rows with no matching dimension key show as NULL in dashboards. This subroutine adds a clean catch-all row to every dimension table in one call — no manual field wiring needed.',
    category: 'scripts',
    date: '2026-04-03',
    file: 'posts/build-null-table.html',
    readTime: 6,
  },
  {
    id: 'calendar-script-benchmark',
    title: 'Calendar Scripts — Which One Is Fastest?',
    excerpt: 'Three common ways to build a master calendar in Qlik — benchmarked. The RESIDENT min/max approach averaged 14 seconds every run. The FieldValue methods were essentially instant.',
    category: 'scripts',
    date: '2026-04-07',
    file: 'posts/calendar-benchmark.html',
    readTime: 6,
  },
  {
    id: 'mapping-table-autoconcatenate',
    title: 'Mapping Tables Auto-Concatenate — and That Can Bite You',
    excerpt: 'Concatenate() throws an error on mapping tables — but naming two MAPPING LOADs the same silently merges them. Useful trick, dangerous trap. And there\'s a DROP MAPPING TABLE statement most people don\'t know about.',
    category: 'scripts',
    date: '2026-04-08',
    file: 'posts/mapping-table-autoconcatenate.html',
    readTime: 5,
  },
  {
    id: 'date-filter-benchmark',
    title: 'Stop Using >= for Date Filters — Use WHERE EXISTS Instead',
    excerpt: 'WHERE TransactionDate >= \'$(vDate)\' is one of the most common patterns in Qlik scripts — but it\'s not the fastest. A temp calendar with WHERE EXISTS beat it by 25% on 10M rows. And there\'s a naming trap that silently kills the advantage.',
    category: 'scripts',
    date: '2026-04-08',
    file: 'posts/date-filter-benchmark.html',
    readTime: 8,
  },
  {
    id: 'applymap-existence-trick',
    title: 'ApplyMap with 1 — The Existence Check Trick (and How to Make It Faster)',
    excerpt: 'One of my favourite Qlik patterns: mapping distinct keys to 1 for fast existence checks in incremental loads. Plus a benchmark showing FieldValue + AutoGenerate beats DISTINCT on 10M rows.',
    category: 'scripts',
    date: '2026-04-03',
    file: 'posts/applymap-existence-trick.html',
    readTime: 7,
  },
];
